Title: VisionEval
Date: 2019-04-26
Description: A minimal VE-config.yml
RunTests: FALSE
Roots: # Require ve.root and ve.output at a minimum
    ve.root:
        path: ../VisionEval-dev-scenmgmt
        branch: scenario-mgmt
    ve.output: ../VE-Built-Scenario-Mgmt
Locations: # "Root" elements are variables defined in "Roots" section
    ve.dependencies:  # Required
        root: ve.output
        path: pkg-dependencies
        description: repo for downloaded and built external dependencies
    ve.repository:    # Required
        root: ve.output
        path: pkg-repository
        description: src/binary repo built from VE packages
    ve.runtime:       # Required
        root: ve.output
        path: runtime
        description: local runtime environment + base for installers
    ve.pkgs:          # Required
        root: ve.output
        path: ve-pkg
        description: copy src tree here from ve.dependencies + ve.repository for installer/docker
    ve.lib:           # Required
        root: ve.output
        path: ve-lib
        description: install bin tree here from ve.repository
    ve.src:           # Required
        root: ve.output
        path: src
        description: build source packages here (plus tests, if requested)
    ve.external:      # Required if there are any Github packages
        root: ve.output
        path: external
