Title: VisionEval
Date: 2019-03-04
Roots:
    ve.root: n:\Git-Repos\visioneval
    ve.alt.root: n:\Git-Repos\VisionEval-dev
    ve.cache: n:\Git-Repos\VE-Cache\
    ve.install: n:\Git-Repos\VE-1.02\
Locations:
    ve.depends:
        root: ve.cache
        path: pkg-dependencies
        description: repo for downloaded and built external dependencies
    ve.built:
        root: ve.install
        path: pkg-repository
        description: src/binary repo built from ve.depends plus VE packages
    ve.runtime:
        root: ve.install
        path: runtime
        description: local runtime environment + base for installers
    ve.pkgs:
        root: ve.install
        path: ve-pkg
        description: copy src tree here from ve.built for installer
    ve.lib:
        root: ve.install
        path: ve-lib
        description: install bin tree here from ve.built
Module:
    visioneval:
        root: ve.root
        path: sources/framework
        CRAN: 
            - jsonlite
            - stringr
            - filesstrings
            - knitr
        BioC:
            - rhdf5
    VE2001NHTS:
        root: ve.root
        path: sources/modules"
        CRAN: 
           - usethis
    VESyntheticFirms:
        root: ve.root
        path: sources/modules"
        CRAN: 
            - reshape
    VESimHouseholds:
        root: ve.root
        path: sources/modules"
        CRAN: 
            - car
            - pbkrtest
            - quantreg
    VELandUse:
        root: ve.root
        path: sources/modules"
        CRAN: 
            - geosphere
            - fields
    VETransportSupply:
        root: ve.root
        path: sources/modules"
    VETransportSupplyUse:
        root: ve.root
        path: sources/modules"
    VEHouseholdTravel:
        root: ve.root
        path: sources/modules"
        CRAN: 
            - pscl
    VEHouseholdVehicles:
        root: ve.root
        path: sources/modules"
        CRAN: 
            - ordinal
            - reshape2
    VEPowertrainsAndFuels:
        root: ve.root
        path: sources/modules"
    VETravelPerformance:
        root: ve.root
        path: sources/modules"
    VEReports:
        root: ve.root
        path: sources/modules"
Source:
    models:
        root: ve.root
        path: sources
        CRAN:
            - data.table
    VEGUI:
        root: ve.root
        path: sources
        CRAN:
            - data.table
            - DT
            - envDocument
            - future.callr
            - jsonlite
            - namedCapture
            - rhandsontable
            - rhdf5
            - shiny
            - shinyBS
            - shinyFiles
            - shinyjs
            - shinytest
            - testit
            - testthat
        External:
            - namedCapture
    VEScenarioViewer:
        root: ve.root
        path: sources
